apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitor
  labels:
    name: alertmanager
spec:
  selector:
    name: alertmanager
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: 9093