{
 "title": "K8s集群资源监控数据仪表板",
 "tags": [
  "Prometheus",
  "Kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "K8s集群",
    "query": {
     "query": "label_values(kube_node_annotations,job)"
    }
   },
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(kube_node_annotations{job=\"$job\"},node)"
    }
   },
   {
    "name": "namespace",
    "label": "命名空间",
    "query": {
     "query": "label_values(kube_namespace_labels{job=\"$job\"},namespace)"
    }
   },
   {
    "name": "container",
    "label": "微服务/服务名称",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"$job\",namespace=\"$namespace\"},container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"$job\",namespace=\"$namespace\",container=\"$container\"},pod)"
    }
   },
   {
    "name": "time",
    "label": "time",
    "query": "2m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "节点资源总览：所选节点[$node]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$node] 工作节点信息明细（关联节点）",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_node_status_condition{job=\"$job\",status=\"true\",node=~\"$node\"} == 1",
       "legendFormat": "节点状态"
      },
      {
       "expr": "count(kube_pod_info{job=\"$job\",created_by_kind!~\"<none>|Job\",node=~\"^$node$\"}) by (node)",
       "legendFormat": "Pod数量"
      },
      {
       "expr": "kube_node_status_allocatable{job=\"$job\",node=~\"^$node$\",resource=\"cpu\",unit=\"core\"} - 0",
       "legendFormat": "CPU总核数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{job=\"$job\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"}) by (node) / sum(kube_node_status_allocatable{job=\"$job\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"}) by (node) * 100",
       "legendFormat": "CPU分配率"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{job=\"$job\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"}) by (node) ",
       "legendFormat": "CPU已分配"
      },
      {
       "expr": "sum (kube_node_status_allocatable{job=\"$job\",node=~\"^$node$\",resource=\"memory\",unit=\"byte\"}) by (node)",
       "legendFormat": "内存总量"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{job=\"$job\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"}) by (node) ",
       "legendFormat": "内存已分配"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{job=\"$job\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"}) by (node) / sum(kube_node_status_allocatable{job=\"$job\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"}) by (node) * 100",
       "legendFormat": "内存已分配(百分比)"
      },
      {
       "expr": "sum(kube_node_status_allocatable{job=\"$job\",resource=\"pods\", unit=\"integer\",node=~\"^$node$\"})by (node)",
       "legendFormat": "Pod上限"
      },
      {
       "expr": "kube_node_role{job=\"$job\",role!=\"control-plane\"} - 0",
       "legendFormat": "role"
      }
     ]
    },
    {
     "title": "[$job] 集群命名空间明细（关联K8s集群）",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "count(kube_pod_info{job=~\"$job\",node=~\"^$node$\"}) by (namespace)",
       "legendFormat": "Pod数量"
      },
      {
       "expr": "count(kube_service_info{job=~\"$job\"}) by(namespace)",
       "legendFormat": "SVC数量"
      },
      {
       "expr": "count(count(kube_pod_container_info{job=~\"$job\"}) by(container,namespace))by(namespace)",
       "legendFormat": "微服务数量"
      },
      {
       "expr": "count(kube_configmap_info{job=~\"$job\"}) by(namespace)",
       "legendFormat": "ConfgiMap数量"
      },
      {
       "expr": "count(kube_secret_info{job=~\"$job\"}) by(namespace)",
       "legendFormat": "Secret数量"
      }
     ]
    },
    {
     "title": "$namespace命名空间：网络总览（关联命名空间）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (rate(container_network_receive_bytes_total{job=~\"$job.*\",namespace=~\"$namespace\"}[$time]))*8",
       "legendFormat": "接收的流量"
      },
      {
       "expr": "sum (rate(container_network_transmit_bytes_total{job=~\"$job.*\",namespace=~\"$namespace\"}[$time]))*8",
       "legendFormat": "发送的流量"
      }
     ]
    }
   ]
  },
  { "title": "微服务资源总览：所选命名空间[$namespace]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "[$container] 微服务资源明细",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{job=\"$job\",namespace=\"$namespace\",pod=~\"$container.*\"}) by (pod)",
     "legendFormat": "Pod名称"
    },
    {
     "expr": "kube_pod_container_status_ready{job=\"$job\",namespace=\"$namespace\",pod=~\"$container.*\"} - 0",
     "legendFormat": "READY"
    },
    {
     "expr": "kube_pod_container_status_running{job=\"$job\",namespace=\"$namespace\",pod=~\"$container.*\"} - 0",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{job=\"$job\",namespace=\"$namespace\",pod=~\"$container.*\"}) by (pod) - 0",
     "legendFormat": "restart"
    },
    {
     "expr": "kube_pod_info{job=\"$job\",namespace=\"$namespace\",pod=~\"$container.*\"} - 0",
     "legendFormat": "pod_ip"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=~\"$job-.*\",namespace=\"$namespace\",container!=\"\",pod=~\"$container.*\"}[$time])) by (pod) * 1000",
     "legendFormat": "CPU已使用(m)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=~\"$job-.*\",namespace=\"$namespace\",container!=\"POD\",pod=~\"$container.*\"}) by (pod) / 2",
     "legendFormat": "Memory (bytes)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"$job\",namespace=\"$namespace\",resource=\"cpu\",pod=~\"$container.*\"}) by (pod) * 1000",
     "legendFormat": "CPU最大资源限制"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"$job\",namespace=\"$namespace\",resource=\"memory\",pod=~\"$container.*\"}) by (pod)",
     "legendFormat": "内存最大资源限制"
    },
    {
     "expr": "(sum(container_memory_working_set_bytes{job=~\"$job-.*\",namespace=\"$namespace\",container!=\"POD\",pod=~\"$container.*\"}) by (pod) / 2) / sum(kube_pod_container_resource_limits{job=\"$job\",namespace=\"$namespace\",resource=\"memory\",pod=~\"$container.*\"}) by (pod) * 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=~\"$job-.*\",namespace=\"$namespace\",pod=~\"$container.*\"}[$time])) by (pod) * 8",
     "legendFormat": "接收的流量"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=~\"$job-.*\",namespace=\"$namespace\",pod=~\"$container.*\"}[$time])) by (pod) * 8",
     "legendFormat": "发送的流量"
    }
   ]
  }
 ]
}