{
 "title": "Kafka监控数据仪表板",
 "description": "Kafka resource usage and throughput",
 "tags": [
  "Kafka",
  "Prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "监控任务",
    "query": {
     "query": "label_values(kafka_brokers, job)"
    }
   },
   {
    "name": "instance",
    "label": "Kafka 集群",
    "query": {
     "query": "label_values(kafka_brokers{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{instance=\"$instance\",consumergroup=~\"$consumergroup\"}, topic)"
    }
   },
   {
    "name": "consumergroup",
    "label": "消费组",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{instance=\"$instance\"},consumergroup)"
    }
   },
   {
    "name": "time",
    "label": "time",
    "query": "1m,2m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka 运行时间",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Broker 数量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Topic 分区数",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{instance=\"$instance\",topic=~\"$topic\",job=\"$job\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "每秒消费完成的次数 (CURRENT-OFFSET)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{instance=\"$instance\", topic=~\"$topic\",job=\"$job\"}[$time])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "当前队列消费堆积数量  (LAG)",
   "type": "timeseries",
   "description": "注意：如果堆积数量为负数。即说明kafka的消费太快了。以下是KafkaManager官方解释：\n\n消费者偏移是从基于 Kafka 的消费者的偏移主题中读取的。 这意味着报告的滞后可能是负数，因为我们从偏移主题中消耗偏移量比轮询生产者偏移量要快。 这是正常现象，不是问题。",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\",job=\"$job\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}}：({{topic}})"
    }
   ]
  }
 ]
}