{
 "title": "MongoDB监控数据仪表板",
 "description": "Note for a official Grafana MongoDB plugin, please view:\nhttps://grafana.com/grafana/plugins/grafana-mongodb-datasource\n\nThis is a MongoDB Prometheus Exporter Dashboard. \nWorks well with https://github.com/dcu/mongodb_exporter\n\nIf you have the node_exporter running on the mongo instance, you will also get some useful alert panels related to disk io and cpu.",
 "tags": [
  "prometheus",
  "MongoDB"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "监控任务", "query": { "query": "label_values(mongodb_date,job)" } },
   {
    "name": "instance",
    "label": "MongoDB实例",
    "query": {
     "query": "label_values(mongodb_date{job=\"$job\"},instance)"
    }
   },
   {
    "name": "time",
    "query": "1m,2m,3m,5m10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "操作QPS数（个）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(mongodb_ss_opcounters{instance=~\"$instance\",legacy_op_type=\"command\"}[$time])",
     "legendFormat": "command"
    },
    {
     "expr": "irate(mongodb_ss_opcounters{instance=~\"$instance\",legacy_op_type=\"delete\"}[$time])",
     "legendFormat": "delete"
    },
    {
     "expr": "irate(mongodb_ss_opcounters{instance=~\"$instance\",legacy_op_type=\"getmore\"}[$time])",
     "legendFormat": "getmore"
    },
    {
     "expr": "irate(mongodb_ss_opcounters{instance=~\"$instance\",legacy_op_type=\"insert\"}[$time])",
     "legendFormat": "insert"
    },
    {
     "expr": "irate(mongodb_ss_opcounters{instance=~\"$instance\",legacy_op_type=\"query\"}[$time])",
     "legendFormat": "query"
    },
    {
     "expr": "irate(mongodb_ss_opcounters{instance=~\"$instance\",legacy_op_type=\"update\"}[$time])",
     "legendFormat": "update"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "description": "监控的是整个操作系统的",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(mongodb_sys_memory_MemTotal_kb{job=\"$job\",instance=~\"$instance\"} - (mongodb_sys_memory_MemFree_kb{job=\"$job\",instance=~\"$instance\"} + mongodb_sys_memory_Buffers_kb{job=\"$job\",instance=~\"$instance\"} + mongodb_sys_memory_Cached_kb{job=\"$job\",instance=~\"$instance\"})) / mongodb_sys_memory_MemTotal_kb{job=\"$job\",instance=~\"$instance\"} * 100",
     "legendFormat": "内存使用率%"
    }
   ]
  },
  {
   "title": "文档操作QPS(增删改查)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_document{job=\"$job\",instance=~\"$instance\"}[$time])",
     "legendFormat": "操作类型：{{doc_op_type}}"
    }
   ]
  },
  {
   "title": " 连接数（个）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"current\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "当前的连接数"
    }
   ]
  }
 ]
}