{
 "title": "MySQL数据库监控仪表板",
 "tags": [
  "Prometheus",
  "MySQL",
  "RDS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "监控任务", "query": { "query": "label_values(mysql_up, job)" } },
   {
    "name": "instance",
    "label": "数据库实例",
    "query": {
     "query": "label_values(mysql_up{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "time",
    "label": "时间范围",
    "query": "1m,2m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "TPS（平均每秒事务数）/QPS（平均每秒SQL语句执行次数）",
   "type": "timeseries",
   "description": "QPS为：每秒SQL语句执行次数\nTPS为：commit+rollback事务数",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "irate(mysql_global_status_queries{job=~\"$job\", instance=~\"$instance\"}[$time])",
     "legendFormat": "平均每秒SQL语句执行次数"
    },
    {
     "expr": "sum (irate(mysql_global_status_handlers_total{instance=\"$instance\",handler=\"commit\"}[$time]))  + sum(irate(mysql_global_status_handlers_total{instance=\"$instance\",handler=\"rollback\"}[$time]))",
     "legendFormat": "平均每秒事务数"
    }
   ]
  },
  {
   "title": "平均每秒慢查询数量",
   "type": "timeseries",
   "description": "slow_queries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(irate(mysql_global_status_slow_queries{instance=\"$instance\",job=~\"$job\"}[$time]))",
     "legendFormat": "慢查询数量"
    }
   ]
  },
  {
   "title": "备节点复制线程状态",
   "type": "timeseries",
   "description": "如果此图表无数据即为该MySQL实例为单节点，并未配置主从复制",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_slave_status_slave_sql_running{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "备节点SQL线程状态"
    },
    {
     "expr": "mysql_slave_status_slave_io_running{instance=\"$instance\"}",
     "legendFormat": "备节点IO线程状态"
    }
   ]
  },
  {
   "title": "MySQL命令数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_commands_total{command=\"delete\", instance=\"$instance\",job=~\"$job\"}[$time])",
     "legendFormat": "平均每秒钟delete语句执行次数"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\", instance=\"$instance\",job=~\"$job\"}[$time])",
     "legendFormat": "平均每秒钟select语句执行次数"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"update\", instance=\"$instance\",job=~\"$job\"}[$time])",
     "legendFormat": "平均每秒钟update语句执行次数"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"replace_select\", instance=\"$instance\",job=~\"$job\"}[$time])",
     "legendFormat": "平均每秒钟replace_select语句执行次数"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"insert_select\", instance=\"$instance\",job=~\"$job\"}[$time])",
     "legendFormat": "平均每秒钟insert_select语句执行次数"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"replace\", instance=\"$instance\",job=~\"$job\"}[$time])",
     "legendFormat": "平均每秒钟replace语句执行次数"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(max_over_time(mysql_global_status_threads_connected{instance=~\"$instance\",job=~\"$job\"}[$time]))",
     "legendFormat": "连接数"
    },
    {
     "expr": "mysql_global_status_threads_running{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "当前活跃连接数"
    },
    {
     "expr": "sum(mysql_global_status_max_used_connections{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "最大使用连接数"
    },
    {
     "expr": "sum(mysql_global_variables_max_connections{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "最大连接数"
    }
   ]
  },
  {
   "title": "从磁盘读取数据的请求数量",
   "type": "timeseries",
   "description": "当缓冲池无法满足时，MySQL只能从磁盘中读取数据",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$instance\",job=~\"$job\"}[$time])",
     "legendFormat": "从磁盘读取数据的请求数量"
    }
   ]
  },
  {
   "title": "InnoDB缓存读命中率、使用率、脏块率（%）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "100 - 100 * (mysql_global_status_innodb_buffer_pool_reads{instance=\"$instance\",job=~\"$job\"}/mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$instance\",job=~\"$job\"})",
     "legendFormat": "缓冲池读命中率"
    },
    {
     "expr": "round((sum(mysql_global_status_buffer_pool_pages{instance=\"$instance\",job=~\"$job\"})  by (instance) - sum(mysql_global_status_buffer_pool_pages{state=\"free\",instance=\"$instance\",job=~\"$job\"}) by (instance)) / sum(mysql_global_status_buffer_pool_pages{instance=\"$instance\",job=~\"$job\"}) by (instance) *100)",
     "legendFormat": "缓冲池利用率"
    },
    {
     "expr": "sum(mysql_global_status_buffer_pool_dirty_pages{instance=\"$instance\",job=~\"$job\"}) / sum(mysql_global_status_buffer_pool_pages{instance=\"$instance\",job=~\"$job\"})",
     "legendFormat": "缓冲池脏块的百分率"
    }
   ]
  },
  {
   "title": "InnoDB读写量（单位为KB）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "irate(mysql_global_status_innodb_data_read{instance=~\"$instance\",job=~\"$job\"}[$time])",
     "legendFormat": "InnoDB平均每秒钟读取的数据量 (KB)"
    },
    {
     "expr": "irate(mysql_global_status_innodb_data_written{instance=~\"$instance\",job=~\"$job\"}[$time])",
     "legendFormat": "InnoDB平均每秒钟写入的数据量 (KB)"
    }
   ]
  },
  {
   "title": "MySQL网络流量（单位KB）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_bytes_received{job=~\"$job\", instance=~\"$instance\"}[$time]))",
     "legendFormat": "平均每秒钟输入的流量"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_bytes_sent{job=~\"$job\", instance=~\"$instance\"}[$time]))",
     "legendFormat": "平均每秒钟输出的流量"
    }
   ]
  },
  {
   "title": "MySQL 内部内存概述",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_page_size{job=~\"$job\", instance=~\"$instance\"} * on (instance) mysql_global_status_buffer_pool_pages{job=~\"$job\", instance=~\"$instance\", state=\"data\"})",
     "legendFormat": "InnoDB 缓冲池数据"
    },
    {
     "expr": "sum(mysql_global_variables_innodb_log_buffer_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "InnoDB 日志缓冲区大小"
    },
    {
     "expr": "sum(mysql_global_variables_innodb_additional_mem_pool_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "InnoDB 附加内存池大小"
    },
    {
     "expr": "sum(mysql_global_status_innodb_mem_dictionary{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "InnoDB 字典大小"
    },
    {
     "expr": "sum(mysql_global_variables_key_buffer_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "密钥缓冲区大小"
    },
    {
     "expr": "sum(mysql_global_variables_query_cache_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "查询缓存大小"
    },
    {
     "expr": "sum(mysql_global_status_innodb_mem_adaptive_hash{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "自适应哈希索引大小"
    },
    {
     "expr": "sum(mysql_global_variables_tokudb_cache_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "TokuDB 缓存大小"
    }
   ]
  },
  {
   "title": "MySQL 临时表",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_created_tmp_tables{instance=\"$instance\",job=~\"$job\"}[$time])",
     "legendFormat": "执行语句时自动创建的临时表的数量"
    },
    {
     "expr": "rate(mysql_global_status_created_tmp_disk_tables{instance=\"$instance\",job=~\"$job\"}[$time])",
     "legendFormat": "执行语句时在硬盘上自动创建的临时表的数量"
    }
   ]
  },
  {
   "title": "MySQL 锁表数量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_table_locks_immediate{job=~\"$job\", instance=~\"$instance\"}[$time]))",
     "legendFormat": "立即锁定表的数量"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_table_locks_waited{job=~\"$job\", instance=~\"$instance\"}[$time]))",
     "legendFormat": "等待锁定表的数量"
    }
   ]
  }
 ]
}