{
 "title": "Redis监控数据仪表板",
 "description": "测试环境Redis",
 "tags": [
  "Prometheus",
  "Redis"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "监控任务", "query": { "query": "label_values(redis_up,job)" } },
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(redis_up{job=\"$job\"},instance)"
    }
   },
   {
    "name": "time",
    "label": "时间范围",
    "query": "1m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU使用率(%)",
   "type": "timeseries",
   "description": "redis_cpu_sys_seconds_total加redis_cpu_user_seconds_total",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg (irate(redis_cpu_sys_seconds_total{instance=\"$instance\",job=\"$job\"}[$time]) + irate(redis_cpu_user_seconds_total{instance=\"$instance\",job=\"$job\"}[$time]))",
     "legendFormat": "CPU使用率"
    }
   ]
  },
  {
   "title": "内存使用率(%)",
   "type": "timeseries",
   "description": "如此图表无数据。则Redis的最大可用内存未配置",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=~\"$instance\",job=\"$job\"}  / redis_memory_max_bytes{instance=~\"$instance\",job=\"$job\"} )",
     "legendFormat": "内存使用率"
    }
   ]
  },
  {
   "title": "已使用内存总量 (Byte)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(redis_memory_used_bytes{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "已用内存总量"
    },
    {
     "expr": "sum(redis_memory_used_lua_bytes{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "Lua脚本使用内存量"
    }
   ]
  },
  {
   "title": "请求数 (Counts/s)",
   "type": "timeseries",
   "description": "每秒执行的命令数",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=~\"$instance\",job=\"$job\"}[$time])",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "已使用连接数 (Counts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "已使用连接数"
    },
    {
     "expr": "redis_blocked_clients{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "被拦截的连接数"
    }
   ]
  },
  {
   "title": "连接数使用率 (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg (irate(redis_connected_clients{instance=\"$instance\",job=\"$job\"}[$time]))",
     "legendFormat": "连接数使用率"
    }
   ]
  },
  {
   "title": "出/入口流量速率 (KBps)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=~\"$instance\",job=\"$job\"}[$time])",
     "legendFormat": "入口流量"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=~\"$instance\",job=\"$job\"}[$time])",
     "legendFormat": "出口流量"
    }
   ]
  },
  {
   "title": "实例Key统计 (Counts)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_db_keys{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "Key总数量"
    },
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\",job=\"$job\"}) - sum (redis_db_keys_expiring{instance=~\"$instance\",job=\"$job\"})",
     "legendFormat": "未过期的Key总数量"
    },
    {
     "expr": "sum(redis_db_keys_expiring{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "已过期的Key总数量"
    },
    {
     "expr": "sum(redis_evicted_keys_total{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "被驱逐的Key总数量"
    }
   ]
  },
  {
   "title": "命中与未命中的Key数量 (Counts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(redis_keyspace_hits_total{instance=~\"$instance\",job=\"$job\"}[$time])",
     "legendFormat": "命中数"
    },
    {
     "expr": "rate(redis_keyspace_misses_total{instance=~\"$instance\",job=\"$job\"}[$time])",
     "legendFormat": "未命中数"
    }
   ]
  },
  {
   "title": "命中率 (%)",
   "type": "timeseries",
   "description": "命中数 / (命中数+未命中数)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(redis_keyspace_hits_total{instance=\"$instance\",job=\"$job\"}[$time]) / (rate(redis_keyspace_hits_total{instance=\"$instance\",job=\"$job\"}[$time]) + rate(redis_keyspace_misses_total{instance=\"$instance\",job=\"$job\"}[$time]))) * 100",
     "legendFormat": "每秒命中率"
    }
   ]
  },
  {
   "title": "命令数 (Counts/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(redis_commands_total{instance=~\"$instance\",job=\"$job\"} [1m])) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "每秒命令延迟",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(redis_commands_duration_seconds_total{instance=~\"$instance\",job=\"$job\"}[1m])) by (cmd)\n  /\navg(irate(redis_commands_total{instance=~\"$instance\",job=\"$job\"}[1m])) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  }
 ]
}