{
 "title": "skywalking分布式链路监控数据仪表板",
 "tags": [
  "Prometheus",
  "Golang",
  "Pushgateway",
  "Skywalking"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "time", "label": "时间范围", "query": "1m,2m,3m,5m,10m,30m,1h" },
   {
    "name": "group",
    "label": "环境",
    "query": {
     "query": "label_values(service_cpm, group)"
    }
   },
   {
    "name": "service",
    "label": "服务",
    "query": {
     "query": "label_values(service_cpm, service)"
    }
   },
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(service_instance_cpm{service=\"$service\"}, instance)"
    }
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": {
     "query": "label_values(endpoint_cpm{service=\"$service\"}, endpoint)"
    }
   },
   {
    "name": "top5cpm",
    "query": {
     "query": "query_result( topk(5,sum  (avg_over_time( service_cpm{group=\"$group\"}[$time] )) by (service)  ) ) "
    }
   },
   {
    "name": "top5_server_resp",
    "query": {
     "query": "query_result( topk(5,sum  (avg_over_time( service_resp_time{group=\"$group\"}[$time] )) by (service)  ) ) "
    }
   },
   {
    "name": "top10_endpoint_cpm",
    "query": {
     "query": "query_result(topk(10,sum(avg_over_time(endpoint_cpm{group=\"$group\"}[$time])) by (endpoint))) "
    }
   },
   {
    "name": "top10_endpoint_avg",
    "query": {
     "query": "query_result(topk(10,sum(avg_over_time(endpoint_avg{group=\"$group\"}[$time])) by (endpoint))) "
    }
   },
   {
    "name": "top10_endpoint_cpm_service",
    "query": {
     "query": "query_result(topk(10,sum(avg_over_time(endpoint_cpm{service=\"$service\"}[$time])) by (endpoint))) "
    }
   },
   {
    "name": "top10_endpoint_svg_srvice",
    "query": {
     "query": "query_result(topk(10,sum(avg_over_time(endpoint_avg{service=\"$service\"}[$time])) by (endpoint))) "
    }
   }
  ]
 },
 "panels": [
  { "title": "统计数据-全局", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top5 service_cpm",
   "type": "piechart",
   "description": "Top5 服务请求次数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(service_cpm{service=~\"$top5cpm\"}[$time])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Top5 service_resp_time",
   "type": "piechart",
   "description": "Top5 服务平均响应时间(毫秒)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(service_resp_time{service=~\"$top5_server_resp\"}[$time])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Top10 endpoint_cpm",
   "type": "piechart",
   "description": "Top10 接口调用次数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(endpoint_cpm{endpoint=~\"$top10_endpoint_cpm\"}[$time])) by (endpoint,service)",
     "legendFormat": "{{endpoint}} 服务{{service}}"
    }
   ]
  },
  {
   "title": "Top10 endpoint_resp_time",
   "type": "piechart",
   "description": "Top10 接口调用平均响应时间(毫秒)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(endpoint_avg{endpoint=~\"$top10_endpoint_avg\"}[$time])) by (endpoint,service)",
     "legendFormat": "{{endpoint}} 服务{{service}}"
    }
   ]
  },
  {
   "title": "service_cpm_all",
   "type": "timeseries",
   "description": "服务CPM(请求次数/分钟)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "avg_over_time(service_cpm{group=\"$group\"}[$time])",
     "legendFormat": "服务CPM(请求次数/分钟)：{{service}}"
    }
   ]
  },
  {
   "title": "service_resp_time_all",
   "type": "timeseries",
   "description": "服务平均响应时间(毫秒)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(service_resp_time{group=\"$group\"}[$time])",
     "legendFormat": "平均响应时间(毫秒)：{{service}}"
    }
   ]
  },
  {
   "title": "性能分析",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top10 $service endpoint_cpm",
     "type": "piechart",
     "description": "Top10 $service 服务接口调用次数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(avg_over_time(endpoint_cpm{endpoint=~\"$top10_endpoint_cpm_service\"}[$time])) by (endpoint,service)",
       "legendFormat": "{{endpoint}} "
      }
     ]
    },
    {
     "title": "Top10 $service endpoint_resp_time",
     "type": "piechart",
     "description": "Top10 $service 服务接口调用平均响应时间(毫秒)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(avg_over_time(endpoint_avg{endpoint=~\"$top10_endpoint_svg_srvice\"}[$time])) by (endpoint,service)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "service_cpm",
     "type": "timeseries",
     "description": "服务CPM(请求次数/分钟)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "avg_over_time(service_cpm{service=\"$service\"}[$time])",
       "legendFormat": "服务CPM(请求次数/分钟)：$service"
      },
      {
       "expr": "sum(avg_over_time(service_cpm{group=\"$group\"}[$time]) )",
       "legendFormat": "服务CPM(请求次数/分钟)：All services "
      }
     ]
    },
    {
     "title": "service_resp_time",
     "type": "timeseries",
     "description": "服务平均响应时间(毫秒)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg_over_time(service_resp_time{service=\"$service\"}[$time])",
       "legendFormat": "平均响应时间(毫秒)：$service "
      },
      {
       "expr": "avg(avg_over_time(service_resp_time{group=\"$group\"}[$time]))",
       "legendFormat": "平均响应时间(毫秒)：All service "
      }
     ]
    },
    {
     "title": "service_instance_cpm",
     "type": "timeseries",
     "description": "服务实例CPM(请求次数/分钟)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "avg_over_time( service_instance_cpm{service=\"$service\",instance=~\"$instance\"}[$time])",
       "legendFormat": "实例CPM(请求次数/分钟)：{{instance}} "
      }
     ]
    },
    {
     "title": "service_instance_resp_time",
     "type": "timeseries",
     "description": "服务实例平均响应时间(毫秒)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(service_instance_resp_time{instance=~\"$instance\"}[$time])) by (instance)",
       "legendFormat": "平均响应时间(毫秒)：{{instance}} "
      }
     ]
    },
    {
     "title": "endpoint_cpm",
     "type": "timeseries",
     "description": "接口方法CPM(调用次数/分钟)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "avg_over_time( endpoint_cpm{service=\"$service\",endpoint=\"$endpoint\"}[$time])",
       "legendFormat": "接口方法CPM(调用次数/分钟)：{{endpoint}}"
      }
     ]
    },
    {
     "title": "endpoint_avg",
     "type": "timeseries",
     "description": "端点平均响应时间(毫秒)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg_over_time(endpoint_avg{service=\"$service\",endpoint=\"$endpoint\"}[$time])",
       "legendFormat": "端点平均响应时间(毫秒)：{{endpoint}}"
      }
     ]
    }
   ]
  }
 ]
}