{
 "title": "微服务（JVM）监控数据仪表板",
 "tags": [
  "Promtheus",
  "JVM",
  "Java"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "集群环境",
    "query": {
     "query": "label_values( jvm_memory_max_bytes,job)"
    }
   },
   {
    "name": "service",
    "label": "微服务",
    "query": {
     "query": "label_values( jvm_memory_max_bytes{job=\"$job\"},application)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values( jvm_memory_max_bytes{job=\"$job\",application=\"$service\"},pod_name)"
    }
   },
   {
    "name": "top5_uri",
    "query": {
     "query": "query_result( topk(5,sum  (avg_over_time(http_server_requests_seconds_max{job=\"$job\",application=\"$service\",pod_name=~\"$pod\"}[$time] )) by (uri)  ) ) "
    }
   },
   {
    "name": "uri",
    "label": "服务接口",
    "query": {
     "query": "label_values( http_server_requests_seconds_count{job=\"$job\",application=\"$service\"},uri)"
    }
   },
   {
    "name": "time",
    "label": "时间范围",
    "query": "1m,2m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "系统概况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM已运行时长",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"$job\",application=\"$service\",pod_name=\"$pod\"}"
    }
   ]
  },
  {
   "title": "JVM CPU使用率",
   "type": "graph",
   "description": "最大值为100",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"$job\",application=\"$service\",pod_name=\"$pod\"} * 100",
     "legendFormat": "JVM CPU使用率"
    }
   ]
  },
  {
   "title": "最近1分钟的系统平均负载",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{job=\"$job\",application=\"$service\",pod_name=\"$pod\"}",
     "legendFormat": "最近1分钟的系统平均负载"
    }
   ]
  },
  {
   "title": "JVM 可用的CPU核心数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{job=\"$job\",application=\"$service\",pod_name=\"$pod\"}"
    }
   ]
  },
  {
   "title": "总QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{job=\"$job\",application=\"$service\", uri!=\"/actuator/info\",pod_name=\"$pod\"}[$time]))",
     "legendFormat": "实例{{pod_name}} QPS"
    },
    {
     "expr": "avg (irate(http_server_requests_seconds_count{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",outcome=\"CLIENT_ERROR\"}[$time]))",
     "legendFormat": "CLIENT_ERROR 平均每秒/个"
    }
   ]
  },
  {
   "title": "平均每个请求响应的时间/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg (irate(http_server_requests_seconds_sum{job=\"$job\",application=\"$service\",pod_name=\"$pod\"}[$time]))",
     "legendFormat": "实例{{pod_name}} 平均响应时间"
    }
   ]
  },
  {
   "title": "线程概览",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"$job\",application=\"$service\",pod_name=~\"$pod\"}",
     "legendFormat": "总线程数"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"$job\",application=\"$service\",pod_name=~\"$pod\"}",
     "legendFormat": "守护线程数"
    },
    {
     "expr": "jvm_threads_states_threads{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",state=~\".*\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "各日志级别数量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(log4j2_events_total{job=\"$job\",application=\"$service\",pod_name=~\"$pod\"}[10m])) by (level)",
     "legendFormat": "{{level}}"
    },
    {
     "expr": "sum(increase(logback_events_total{job=\"$job\",application=\"$service\",pod_name=~\"$pod\"}[10m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "数据库连接数概览",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jdbc_connections_max{job=\"$job\",application=\"$service\",pod_name=~\"$pod\"}",
     "legendFormat": "允许的最大活跃连接数"
    },
    {
     "expr": "hikaricp_connections_active{job=\"$job\",application=\"$service\",pod_name=~\"$pod\"}",
     "legendFormat": "当前活跃连接数"
    },
    {
     "expr": "hikaricp_connections_pending{job=\"$job\",application=\"$service\",pod_name=~\"$pod\"}",
     "legendFormat": "等待获取连接数"
    }
   ]
  },
  { "title": "${service}服务接口概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "单个接口QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{job=\"$job\",application=\"$service\",uri=\"$uri\",pod_name=\"$pod\"}[$time]))",
     "legendFormat": "服务接口：$uri QPS"
    }
   ]
  },
  {
   "title": "单个接口平均响应时间/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg (irate(http_server_requests_seconds_sum{job=\"$job\",application=\"$service\",uri=\"$uri\",pod_name=\"$pod\"}[$time]))",
     "legendFormat": "服务接口: $uri 平均响应时间"
    }
   ]
  },
  {
   "title": "GC概述",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "long-lived heap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_gc_max_data_size_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\"}) by (pod_name)",
       "legendFormat": "long-lived heap总大小"
      },
      {
       "expr": "sum(jvm_gc_live_data_size_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\"}) by (pod_name)",
       "legendFormat": "gc后long-lived heap总大小"
      }
     ]
    },
    {
     "title": "GC暂停总次数",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(jvm_gc_pause_seconds_count{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",action=\"end of major GC\"}) by (pod_name)",
       "legendFormat": "major GC暂停总次数"
      },
      {
       "expr": "sum(jvm_gc_pause_seconds_count{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",action=\"end of minor GC\"}) by (pod_name)",
       "legendFormat": "minor GC暂停总次数"
      }
     ]
    },
    {
     "title": "GC暂停总时间",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(jvm_gc_pause_seconds_sum{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",action=\"end of major GC\"}) by (pod_name)",
       "legendFormat": "major GC暂停总时间"
      },
      {
       "expr": "sum(jvm_gc_pause_seconds_sum{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",action=\"end of minor GC\"}) by (pod_name)",
       "legendFormat": "minor GC暂停总时间"
      }
     ]
    }
   ]
  },
  {
   "title": "NIO Buffer内存概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "id：direct内存概览",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_buffer_total_capacity_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\", id=\"direct\"}) by (pod_name)",
       "legendFormat": "direct总大小"
      },
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\", id=\"direct\"}) by (pod_name)",
       "legendFormat": "direct已使用"
      }
     ]
    },
    {
     "title": "id：mapped内存概览",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_buffer_total_capacity_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\", id=\"mapped\"}) by (pod_name)",
       "legendFormat": "mapped总大小"
      },
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\", id=\"mapped\"}) by (pod_name)",
       "legendFormat": "mapped已使用"
      }
     ]
    }
   ]
  },
  {
   "title": "heap内存概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"heap\",id=~\".*Eden Space\"}) by (pod_name,id)",
       "legendFormat": "\"{{id}}\" 内存上限"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"heap\",id=~\".*Eden Space\"}) by (pod_name,id)",
       "legendFormat": "\"{{id}}\" 已使用的内存"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"heap\",id=~\".*Eden Space\"}) by (pod_name,id)",
       "legendFormat": "\"{{id}}\" 已分配的内存"
      }
     ]
    },
    {
     "title": "Survivor Space",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"heap\",id=~\".*Survivor Space\"}) by (pod_name,id)",
       "legendFormat": "\"{{id}}\" 内存上限"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"heap\",id=~\".*Survivor Space\"}) by (pod_name,id)",
       "legendFormat": "\"{{id}}\" 已使用的内存"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"heap\",id=~\".*Survivor Space\"}) by (pod_name,id)",
       "legendFormat": "\"{{id}}\" 已分配的内存"
      }
     ]
    },
    {
     "title": "Old Gen",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"heap\",id=~\"Tenured Gen|G1 Old Gen|PS Old Gen\"}) by (pod_name,id)",
       "legendFormat": "\"{{id}}\" 内存上限"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"heap\",id=~\"Tenured Gen|G1 Old Gen|PS Old Gen\"}) by (pod_name,id)",
       "legendFormat": "\"{{id}}\" 已使用的内存"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"heap\",id=~\"Tenured Gen|G1 Old Gen|PS Old Gen\"}) by (pod_name,id)",
       "legendFormat": "\"{{id}}\" 已分配的内存"
      }
     ]
    }
   ]
  },
  {
   "title": "nonheap内存概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "id：Compressed Class Space内存概览",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"nonheap\",id=\"Compressed Class Space\"}) by (pod_name)",
       "legendFormat": "id：\"Compressed Class Space\" 内存上限"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"nonheap\",id=\"Compressed Class Space\"}) by (pod_name)",
       "legendFormat": "id：\"Compressed Class Space\" 已使用的内存"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"nonheap\",id=\"Compressed Class Space\"}) by (pod_name)",
       "legendFormat": "id：\"Compressed Class Space\" 已分配的内存"
      }
     ]
    },
    {
     "title": "id：Metaspace内存概览",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"nonheap\",id=\"Metaspace\"}) by (pod_name)",
       "legendFormat": "id：\"Metaspace\" 内存上限"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"nonheap\",id=\"Metaspace\"}) by (pod_name)",
       "legendFormat": "id：\"Metaspace\" 已使用的内存"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"nonheap\",id=\"Metaspace\"}) by (pod_name)",
       "legendFormat": "id：\"Metaspace\" 已分配的内存"
      }
     ]
    },
    {
     "title": "id：CodeHeap内存概览",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"nonheap\",id=~\"CodeHeap.*|Code Cache\"}) by (pod_name)",
       "legendFormat": "id：\"CodeHeap\" 内存上限"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"nonheap\",id=~\"CodeHeap.*|Code Cache\"}) by (pod_name)",
       "legendFormat": "id：\"CodeHeap\" 已使用的内存"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$job\",application=\"$service\",pod_name=~\"$pod\",area=\"nonheap\",id=~\"CodeHeap.*|Code Cache\"}) by (pod_name)",
       "legendFormat": "id：\"CodeHeap\" 已分配的内存"
      }
     ]
    }
   ]
  }
 ]
}