{
 "title": "服务器资源使用仪表板",
 "tags": [
  "Prometheus",
  "node_exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "监控任务",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},nodename)"
    }
   },
   {
    "name": "disk",
    "label": "磁盘名称",
    "query": {
     "query": "label_values(node_disk_read_bytes_total{job=\"$job\"},device)"
    }
   },
   {
    "name": "interface",
    "label": "网卡",
    "query": {
     "query": "label_values(node_network_info{instance=~\"$node.*\", job=\"$job\",device!=\"lo\"},device)"
    }
   },
   {
    "name": "time",
    "label": "时间范围",
    "query": "30s,1m,2m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "基础监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "系统运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node.*\"})"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node.*\",mode=\"iowait\"}[$time])) * 100"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$node.*\", job=\"$job\"} - node_memory_MemAvailable_bytes{instance=~\"$node.*\", job=\"$job\"}) / node_memory_MemTotal_bytes{instance=~\"$node.*\", job=\"$job\"} * 100"
    }
   ]
  },
  {
   "title": "已用磁盘空间",
   "type": "table-old",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node.*',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node.*',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node.*',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node.*',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node.*',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node.*',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node.*',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "CPU使用率 （$time）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{ instance=~\"$node.*\", job=\"$job\",mode=\"idle\"}[$time])) * 100)",
     "legendFormat": "cpu使用率%"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$node.*\", job=\"$job\"} - node_memory_MemAvailable_bytes{instance=~\"$node.*\", job=\"$job\"}) / node_memory_MemTotal_bytes{instance=~\"$node.*\", job=\"$job\"} * 100",
     "legendFormat": "内存使用率%"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "node_load1{job=\"$job\",instance=~\"$node.*\"}",
     "legendFormat": "1分钟平均负载"
    },
    {
     "expr": "node_load5{job=\"$job\",instance=~\"$node.*\"}",
     "legendFormat": "5分钟平均负载"
    },
    {
     "expr": "node_load15{job=\"$job\",instance=~\"$node.*\"}",
     "legendFormat": "15分钟平均负载"
    }
   ]
  },
  {
   "title": "磁盘($disk)使用率 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "100 * ((node_filesystem_size_bytes{job=\"$job\",device=~\".*$disk.*\",instance=~\"$node.*\"} - node_filesystem_avail_bytes{job=\"$job\",device=~\".*$disk.*\",instance=~\"$node.*\"}) / node_filesystem_size_bytes{job=\"$job\",device=~\".*$disk.*\",instance=~\"$node.*\"})",
     "legendFormat": "磁盘使用率%"
    }
   ]
  },
  {
   "title": "磁盘($disk)读写字节数(Bps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"$disk\", instance=~\"$node.*\"}[$time])",
     "legendFormat": "每秒读取的字节数"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"$disk\", instance=~\"$node.*\"}[$time])",
     "legendFormat": "每秒写入的字节数"
    }
   ]
  },
  {
   "title": "磁盘($disk)请求读写数 (Count/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"$disk\", instance=~\"$node.*\", job=\"$job\"}[$time])",
     "legendFormat": "每秒完成读取的请求数"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"$disk\", instance=~\"$node.*\", job=\"$job\"}[$time])",
     "legendFormat": "每秒完成写入的请求数"
    }
   ]
  },
  { "title": "网络I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "网卡($interface)出入站流量(MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum  by (instance) (rate(node_network_transmit_bytes_total{device=\"$interface\",instance=~\"$node.*\"}[$time])) / 1024 / 1024",
     "legendFormat": "network_出站流量"
    },
    {
     "expr": "sum  by (instance) (rate(node_network_receive_bytes_total{device=\"$interface\",instance=~\"$node.*\"}[$time])) / 1024 / 1024",
     "legendFormat": "network_入站流量"
    }
   ]
  },
  {
   "title": "网卡($interface)流入流出数据包数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (irate(node_network_transmit_packets_total{device=\"$interface\",instance=~\"$node.*\"}[1m]))",
     "legendFormat": "network_流出的数据包"
    },
    {
     "expr": "avg (irate(node_network_receive_packets_total{device=\"$interface\",instance=~\"$node.*\"}[1m]))",
     "legendFormat": "network_流入的数据包"
    },
    {
     "expr": "sum (rate(node_network_receive_errs_total{device=\"$interface\", instance=~\"$node.*\"}[$time]))",
     "legendFormat": "network_错误的数据包(in)"
    },
    {
     "expr": "sum (rate(node_network_transmit_errs_total{device=\"$interface\", instance=~\"$node.*\"}[$time]))",
     "legendFormat": "network_错误的数据包(out)"
    }
   ]
  },
  {
   "title": "进程数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg (rate(node_softnet_processed_total{instance=~\"$node.*\"}[$time])) ",
     "legendFormat": "进程数"
    }
   ]
  },
  {
   "title": "TCP连接数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$node.*\"}",
     "legendFormat": " ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$node.*\"}",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~\"$node.*\"} + node_sockstat_TCP_alloc{instance=~\"$node.*\"}",
     "legendFormat": "TCP_TOTAL"
    }
   ]
  }
 ]
}