apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitor
  labels:
    name: prometheus
spec:
  selector:
    name: prometheus
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 3009