apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus-alert-center
  name: prometheus-alert-center
  namespace: monitor
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  selector:
    name: prometheus-alert-center
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080